### ISSUE TITLE
IOException with AWSBatch

### ISSUE THREAD

**Issue by matthewghgriffiths** [broadinstitute/cromwell#4341]
I'm having some problems running the AWSBatch examples from the aws opendata page - https://docs.opendata.aws/genomics-workflows/aws-batch/configure-aws-batch-start/ - as far as I can tell I have correctly set the permissions, however when I try running the examples I get the error below. It looks like the output files aren't being written the S3 bucket. 

I'm probably missing something obvious, but I can't work out what I'm doing wrong. Would anyone have any suggestions for where might be good to look for errors?

```[2018-10-31 10:24:09,16] [[38;5;1merror[0m] WorkflowManagerActor Workflow b7e4cdce-ff14-4509-aec3-b226ed31043c failed (during ExecutingWorkflowState): cromwell.engine.io.IoAttempts$EnhancedCromwellIoException: [Attempted 1 time(s)] - IOException: Could not read from s3://concr-genomics-results/cromwell-execution/wf_hello/b7e4cdce-ff14-4509-aec3-b226ed31043c/call-hello/hello-rc.txt: s3://s3.amazonaws.com/concr-genomics-results/cromwell-execution/wf_hello/b7e4cdce-ff14-4509-aec3-b226ed31043c/call-hello/hello-rc.txt
Caused by: java.io.IOException: Could not read from s3://concr-genomics-results/cromwell-execution/wf_hello/b7e4cdce-ff14-4509-aec3-b226ed31043c/call-hello/hello-rc.txt: s3://s3.amazonaws.com/concr-genomics-results/cromwell-execution/wf_hello/b7e4cdce-ff14-4509-aec3-b226ed31043c/call-hello/hello-rc.txt
	at cromwell.engine.io.nio.NioFlow$$anonfun$withReader$2.applyOrElse(NioFlow.scala:146)
	at cromwell.engine.io.nio.NioFlow$$anonfun$withReader$2.applyOrElse(NioFlow.scala:145)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recoverWith(Try.scala:232)
	at cromwell.engine.io.nio.NioFlow.withReader(NioFlow.scala:145)
	at cromwell.engine.io.nio.NioFlow.limitFileContent(NioFlow.scala:154)
	at cromwell.engine.io.nio.NioFlow.$anonfun$readAsString$1(NioFlow.scala:98)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.file.NoSuchFileException: s3://s3.amazonaws.com/concr-genomics-results/cromwell-execution/wf_hello/b7e4cdce-ff14-4509-aec3-b226ed31043c/call-hello/hello-rc.txt
	at org.lerch.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:350)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at better.files.File.newInputStream(File.scala:337)
	at cromwell.core.path.BetterFileMethods.newInputStream(BetterFileMethods.scala:240)
	at cromwell.core.path.BetterFileMethods.newInputStream$(BetterFileMethods.scala:239)
	at cromwell.filesystems.s3.S3Path.newInputStream(S3PathBuilder.scala:156)
	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream(EvenBetterPathMethods.scala:94)
	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream$(EvenBetterPathMethods.scala:91)
	at cromwell.filesystems.s3.S3Path.mediaInputStream(S3PathBuilder.scala:156)
	at cromwell.engine.io.nio.NioFlow.$anonfun$withReader$1(NioFlow.scala:145)
	at cromwell.util.TryWithResource$.$anonfun$tryWithResource$1(TryWithResource.scala:14)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.util.TryWithResource$.tryWithResource(TryWithResource.scala:10)
	... 14 more
```

**Comment by alexfrieden** [comment]
Check before this in the stdout, I ran into this and it was due to a docker image not accessible.  Still haven't figured out that problem but hopefully it will point you in the right direction.  See link: 
https://gatkforums.broadinstitute.org/wdl/discussion/13540/unable-to-do-docker-lookup#latest

**Comment by TMiguelT** [comment]
I think this looks like a permission issue. Double check that the cromwell server has AWS authentication to read and write to the bucket you listed

**Comment by matthewghgriffiths** [comment]
As far as I can tell the cromwell server has permission to read from the bucket:

```
[ec2-user@cromwell-server ~]$ aws s3 cp upload.txt s3://concr-genomics-results
upload: ./upload.txt to s3://concr-genomics-results/upload.txt
[ec2-user@cromwell-server ~]$ aws s3 ls s3://concr-genomics-results
2018-11-01 10:32:25          0 upload.txt
```

I also get the same issue when submitting from my workstation, which also has AWS authentication to read and write from the bucket. 

Is there another setting I might be missing?

**Comment by seandavi** [comment]
In your cromwell AWS config file, check that you have set the region correctly (and not to "default", but to something explicit like `us-east-1`).

**Comment by TMiguelT** [comment]
Ah, I see. Just a guess, but are you sure your S3 URLs (or more likely your S3 bucket in the configuration file) are in the right format? `s3://s3.amazonaws.com/concr-genomics-results/cromwell-execution/wf_hello/b7e4cdce-ff14-4509-aec3-b226ed31043c/call-hello/hello-rc.txt` doesn't look valid to me. It should be more like `s3://concr-genomics-results`.

Alternatively, maybe the AWS Batch role doesn't have read access to the S3 bucket? The Cromwell server and the Batch instances are different

**Comment by matthewghgriffiths** [comment]
I have already changed that setting, as it was causing a different error.

my aws.conf:

```
include required(classpath("application"))

aws {
  application-name = "cromwell"
  auths = [{
      name = "default"
      scheme = "default"
  }]
  region = "us-east-1"
}

engine { filesystems { s3 { auth = "default" } } }

backend {
  default = "AWSBATCH"
  providers {
    AWSBATCH {
      actor-factory = "cromwell.backend.impl.aws.AwsBatchBackendLifecycleActorFactory"
      config {
        numSubmitAttempts = 3
        numCreateDefinitionAttempts = 3
        root = "s3://concr-genomics-results/cromwell-execution"
        auth = "default"
        concurrent-job-limit = 16
        default-runtime-attributes { queueArn = "arn:aws:batch:us-east-1:<##########>:job-queue/GenomicsDefaultQueue-<###########>" }
        filesystems { s3 { auth = "default" } }
      }
    }
  }
}
```

**Comment by matthewghgriffiths** [comment]
> Alternatively, maybe the AWS Batch role doesn't have read access to the S3 bucket? The Cromwell server and the Batch instances are different

Here's the IAM S3 Policy for the Genomics Batch EC2 role `GenomicsEnv-Batch-IamStac-GenomicsEnvBatchInstance-16INP51KVS4TZ`

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::concr-genomics-results",
                "arn:aws:s3:::concr-genomics-results/*"
            ],
            "Effect": "Allow",
            "Sid": "S3BucketAllowAllObjectOps"
        }
    ]
}
```

**Comment by TMiguelT** [comment]
Hmm, all of that seems pretty sensible

**Comment by TMiguelT** [comment]
I'm guessing if you `aws s3 ls` that file, then it doesn't actually exist? Is it an input file or an output?

**Comment by matthewghgriffiths** [comment]
No files get written to the aws bucket at any point of the running of the job.

**Comment by seandavi** [comment]
For troubleshooting directly:

1. Set the min cpus in your compute environment (the one in use) to 1 so that an instance spins up.
2. SSH into the instance that spins up (or one already running) in the compute environment.
3. Try to `aws s3 cp` a file into your cromwell executions bucket. Doing this from the instance simulates the permissions used by the batch job.

If you get an error about permissions, then there is likely a policy problem with your instance role.

**Comment by matthewghgriffiths** [comment]
@seandavi 
I SSH'd into the compute environment and was able to copy files into the cromwell executions bucket.

**Comment by matthewghgriffiths** [comment]
OK I think I got it working. 

It turns out the custom AMI I created was incorrect.

When making a custom AMI using the cloud formation stacks as described [here](https://docs.opendata.aws/genomics-workflows/aws-batch/create-custom-ami/).

The AMI type needs to be specified as 'cromwell' and the Scratch mount point needs to be specified as `\cromwell_mount`

This information is stated [elsewhere](https://docs.opendata.aws/genomics-workflows/cromwell/cromwell-aws-batch/), but perhaps this [page](https://docs.opendata.aws/genomics-workflows/aws-batch/create-custom-ami/) should be updated to include this information?

**Comment by seandavi** [comment]
I got caught as well. See #4322, for example.

**Comment by illusional** [comment]
@matthewghgriffiths did it work with `\cromwell_mount` for `\cromwell_root`. I'm getting a very similar error, and I've double checked that I had "cromwell_root" as listed [here](https://docs.opendata.aws/genomics-workflows/cromwell/cromwell-aws-batch/#custom-ami-with-cromwell-additions). I created my AMI today, and I definitely have read / write access from my EC2 instance.

I also can't see any Cromwell-execution folders in the bucket, but I do see the cromwell-workflow-logs on my EC2 instance.

I created the AMI with the cromwell type, and I've checked that my IAM profile has access to the execution and storage bucket, and confirmed this in the CLI. 

```
Caused by: java.io.IOException: Could not read from s3://<bucket-name>/cromwell-execution/gatkRecalNormal/df58d76a-c3fe-4fb7-94c6-f4bd9ad1d5de/call-gatkBaseRecalibrator/gatkBaseRecalibrator-rc.txt: s3://s3.amazonaws.com/<bucket-name>/cromwell-execution/gatkRecalNormal/df58d76a-c3fe-4fb7-94c6-f4bd9ad1d5de/call-gatkBaseRecalibrator/gatkBaseRecalibrator-rc.txt
	at cromwell.engine.io.nio.NioFlow$$anonfun$withReader$2.applyOrElse(NioFlow.scala:146)
	at cromwell.engine.io.nio.NioFlow$$anonfun$withReader$2.applyOrElse(NioFlow.scala:145)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recoverWith(Try.scala:232)
	at cromwell.engine.io.nio.NioFlow.withReader(NioFlow.scala:145)
	at cromwell.engine.io.nio.NioFlow.limitFileContent(NioFlow.scala:154)
	at cromwell.engine.io.nio.NioFlow.$anonfun$readAsString$1(NioFlow.scala:98)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.file.NoSuchFileException: s3://s3.amazonaws.com/mfranklin-cromwell-wdir/cromwell-execution/gatkRecalNormal/df58d76a-c3fe-4fb7-94c6-f4bd9ad1d5de/call-gatkBaseRecalibrator/gatkBaseRecalibrator-rc.txt
	at org.lerch.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:350)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at better.files.File.newInputStream(File.scala:337)
	at cromwell.core.path.BetterFileMethods.newInputStream(BetterFileMethods.scala:240)
	at cromwell.core.path.BetterFileMethods.newInputStream$(BetterFileMethods.scala:239)
	at cromwell.filesystems.s3.S3Path.newInputStream(S3PathBuilder.scala:156)
	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream(EvenBetterPathMethods.scala:94)
	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream$(EvenBetterPathMethods.scala:91)
	at cromwell.filesystems.s3.S3Path.mediaInputStream(S3PathBuilder.scala:156)
	at cromwell.engine.io.nio.NioFlow.$anonfun$withReader$1(NioFlow.scala:145)
	at cromwell.util.TryWithResource$.$anonfun$tryWithResource$1(TryWithResource.scala:14)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.util.TryWithResource$.tryWithResource(TryWithResource.scala:10)
	... 14 more
```

IAM S3 permissions: 
```
"s3:PutObject", "s3:GetObject", "s3:ListBucket", "s3:DeleteObject"
```

**Comment by seandavi** [comment]
What does the storage block in cromwell config look like? In particular, do you have a region set? If I recall correctly, I had to actually set the region (not default) or I had similar errors.

**Comment by illusional** [comment]
I do have a region set in the config and when I was setting up the AMI, after`#4294 I'm using ap-southeast-2.

**Comment by illusional** [comment]
I'm don't know how to exactly determine it was the issue, but when creating the [AMI Profile](https://console.aws.amazon.com/cloudformation/home?#/stacks/new?stackName=GenomicsWorkflow-AMI&templateURL=https://s3.amazonaws.com/aws-genomics-workflows/templates/create-genomics-ami/create-custom-ami-new-vpc.yaml), specifying `/cromwell_mount` is what made it work for me. Does this mean [the documentation](http://aws-genomics-workflows.s3-website-us-east-1.amazonaws.com/cromwell/cromwell-aws-batch/#custom-ami-with-cromwell-additions) is incorrect, or have I accidentally fixed my config in some other way?

**Comment by geoffjentry** [comment]
Hi @wleepang - would you be able to take a look at this?

**Comment by wleepang** [comment]
@illusional - The mount point should be `/cromwell_root` when you create the custom AMI.  The is the filesystem path that Cromwell uses by default for task data.  When creating your config file you will need to specify the region you are operating it - i.e. where your S3 bucket and Batch queues are.

All of the above should be preconfigured if you use the [Cromwell "All-in-One" template](https://docs.opendata.aws/genomics-workflows/cromwell/cromwell-aws-batch/#tldr).

**Comment by geoffjentry** [comment]
From the hackathon - we believe that people who were previously encountering this issue will find that it's resolved via the [new(ish) launch template](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create?stackName=Cromwell&templateURL=https://s3.amazonaws.com/aws-genomics-workflows/templates/cromwell/cromwell-aio.template.yaml).

**Comment by yihming** [comment]
Hi,

I recently come across the same issue when using Cromwell with AWS Batch. However, it seems none of the reference links in this thread is available, except for the most recent link to cromwell-aio.template.yaml which also failed during the creation.

So may I know where I should get help regarding this issue? Many thanks!


Sincerely,
Yiming

**Comment by multimeric** [comment]
I think the home of all these docs moved. I guess here is where it now lives: https://docs.opendata.aws/genomics-workflows/quick-start.html. Although I get the impression that this stack will become much simpler to setup with the upcoming [Genomics CLI](https://aws.amazon.com/blogs/industries/announcing-amazon-genomics-cli-preview/) (which you can apply to preview).

**Comment by yihming** [comment]
Hi @multimeric ,

Thank you so much for providing the current location of those links. 

I still have a question regarding the solution proposed here. In the current documentation website, I could not find the guidance or CloudFormation for creating a custom AMI, which is described above. And moreover, I also could not find the description saying that "The AMI type needs to be specified as 'cromwell' and the Scratch mount point needs to be specified as \cromwell_mount", which was mentioned above as the solution. 

Is it because the whole creation procedure has been changed since then? In the current documentation, I only found [this link](https://docs.opendata.aws/genomics-workflows/core-env/create-custom-compute-resources.html#custom-amis) which only briefly talked about creating a custom AMI but not gave any CloudFormation link. Do you know where I should look for this information? Thanks!

Also, thank you for letting me know about the Genomics CLI. I have to say that the current deployment procedure on AWS is way more complicated than GCP, especially given that my company's cloud team puts more restrictions which complicates the standard procedure that used to work in my personal AWS account. I'm looking forward to hearing from the development of Genomics CLI.


Sincerely,
Yiming

**Comment by multimeric** [comment]
Because the stack has changed a lot over time, I wouldn't assume the bug discussed in this thread is the same as your bug. I'll provide some more detail in the thread you created.
