### ISSUE TITLE
imports zip file with a subdir causes errors

### ISSUE THREAD

**Issue by notestaff** [broadinstitute/cromwell#4969]
With Cromwell 41, when submitting an imports.zip containing workflow imports, if the zipfile has a subdirectory, I get these errors:

2019-05-14 11:05:38,560 cromwell-system-akka.dispatchers.engine-dispatcher-101 ERROR - WorkflowManagerActor Workflow a3fb73f1-2976-456\
3-a691-a356e2744dda failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.Materiali\
zeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
/tmp/imports_workflow_a3fb73f1-2976-4563-a691-a356e2744dda_9012613107684347004.zip7783627211874195701/tasks/tasks_assembly.wdl
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$ma\
terialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:215)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWor\
kflowDescriptorActor.scala:185)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWor\
kflowDescriptorActor.scala:180)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processE\
vent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescr\
iptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDesc\
riptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2019-05-14 11:05:38,561 cromwell-system-akka.dispatchers.engine-dispatcher-101 INFO  - WorkflowManagerActor WorkflowActor-a3fb73f1-297\
6-4563-a691-a356e2744dda is in a terminal state: WorkflowFailedState

**Comment by jeremiahsavage** [comment]
I just encountered this error, as well. I narrowed it down to this commit.

**Comment by geoffjentry** [comment]
Thanks @jeremiahsavage 

@notestaff Were you using WDL or CWL?

**Comment by jeremiahsavage** [comment]
Example test case:

`wf.cwl`:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: Workflow

inputs:
  - id: astring
    type: string

outputs:
  - id: afile
    type: File
    outputSource: touch/output

steps:
  - id: touch
    run: cwl/touch.cwl
    in:
      - id: input
        source: astring
    out:
      - id: output
```

in `cwl/touch.cwl`:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

requirements:
  - class: DockerRequirement
    dockerPull: ubuntu:bionic-20180426

class: CommandLineTool

inputs:
  - id: input
    type: string
    inputBinding:
      position: 0

outputs:
  - id: output
    type: File
    outputBinding:
      glob: $(inputs.input)
      
baseCommand: [touch]
```
then zip the dir:
```
zip -r cwl.zip cwl
```
test input `wf.json`:
```
{
    "astring": "hello"
}
```

**Comment by notestaff** [comment]
WDL

**Comment by jeremiahsavage** [comment]
ah. Should I create a separate issue?

> WDL

ah. Should I create a separate issue for CWL?

**Comment by geoffjentry** [comment]
Let's keep it on this issue for now although it seems likely that there's a different root cause. We can split the issues once that's confirmed.

@notestaff Could you provide a minimal case in WDL which replicates this?

**Comment by huangzhibo** [comment]
I have encountered the same problem, either local mode or server mode.

version :  comwell41
wdl:  version 1

- error info: 

```
  "submission": "2019-06-28T08:36:56.384Z",
  "status": "Failed",
  "failures": [
    {
      "causedBy": [
        {
          "causedBy": [],
          "message": "/tmp/imports_workflow_63e53e21-b200-46b2-9653-db79983d6c1d_3805297415647673436.zip4786068963842572955/bcftools-task/bcftoolsView.wdl"
        }
      ],
      "message": "Workflow input processing failed"
    }
  ],
```

- my wdl header

```
version 1.0

import "bcftools-task/bcftoolsView.wdl" as select
import "beagle-task/prephasing.wdl" as prephasing

```

- unzip -v impute_human_beagle_v1.zip

```
Archive:  impute_human_beagle_v1.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     655  Defl:N      319  51% 06-28-2019 15:52 d52896d1  bcftools-task/bcftoolsView.wdl
     694  Defl:N      384  45% 06-28-2019 14:24 552eeedb  beagle-task/prephasing.wdl
--------          -------  ---                            -------
    1349              703  48%                            2 files
```

**Comment by myazinn** [comment]
Hi @notestaff and @huangzhibo -
I'm currently investigating this issue and trying to reproduce the problem.
Since I'm not familiar with WDL, I took workflow examples from [here](https://cromwell.readthedocs.io/en/stable/SubWorkflows/) and put `sub_wdl.wdl` in a subdirectory.
Therefore, the `main.wdl` looks like 
```
import "sub_dir/sub_wdl.wdl" as sub

workflow main_workflow {
    call sub.hello_and_goodbye { input: hello_and_goodbye_input = "sub world" }
    # call myTask { input: hello_and_goodbye.hello_output }
    output {
        String main_output = hello_and_goodbye.hello_output
    }
}
```
The body of `sub_wdl.wdl` wasn't changed
```
task hello {
  String addressee
  command {
    echo "Hello ${addressee}!"
  }
  output {
    String salutation = read_string(stdout())
  }
}
task goodbye {
  String addressee
  command {
    echo "Goodbye ${addressee}!"
  }
  output {
    String salutation = read_string(stdout())
  }
}
workflow hello_and_goodbye {
  String hello_and_goodbye_input
  call hello {input: addressee = hello_and_goodbye_input }
  call goodbye {input: addressee = hello_and_goodbye_input }
  output {
    String hello_output = hello.salutation
    String goodbye_output = goodbye.salutation
  }
}
```
I put `sub_wdl.wdl` into a subdirectory
```
mkdir sub_dir; mv sub_wdl.wdl sub_dir/sub_wdl.wdl
```
zipped this subdirectory
```
zip -r sub_dir.zip sub_dir/
```
and ran a workflow with the following commad
```
java -jar /home/path/to/cromwell/cromwell.jar run /home/path/to/files/main.wdl --imports /home/path/to/files/sub_dir.zip
```
The workflow succeeded without any problem.
Maybe my workflow is not reproducing this issue because I'm doing something wrong. I tried to run this workflow using Cromwell 41 and 45. Workflows succeeded in both cases. Can you tell me what should be changed in order to reproduce your problem?

**Comment by drkennetz** [comment]
Hi @myazinn, I have had trouble doing the same thing with cromwell 44 for CWL. I cannot import tools.zip to run workflows. 

`java -jar ~/bin/cromwell-44.jar run echo_cat_wf.cwl -i in.yml -p tools.zip` gives me error:

```
 Workflow input processing failed:
Invalid workflow reference: echo_cat_wf.cwl
```

**Comment by myazinn** [comment]
Hi @drkennetz 
Thank you for the info. The error you get and the usage scenario is very similar to the issue #5085. I'm not sure, but I think that your problem has the same reason.
I already made a PR #5104 that should fix this. 
Although I'm not sure that Cromwell’s team will accept it, you can try to use it. If you know how to assemble a project in a .jar file from source code, then do it and run your workflow. I think it should run normally.
Alternatively, you can try to run Cromwell (the one that you have) in a server mode and submit your workflow using REST API or Swagger (it provides nice GUI).
If you'll make any of this, let me know if that helped. If it didn't help, please give me some examples of what you're running so I can reproduce it.

**Comment by drkennetz** [comment]
@myazinn Thanks for the PR recommendation. I will assemble it later on today or this weekend and post back to you with the results. If it fails, I'll give you the workflow that I ran to see if you can reproduce my issue. Thanks!

**Comment by huangzhibo** [comment]
Hi @myazinn,
I rerun your example. 
I found that the cause of the problem was the way the files were compressed.

For this sub wdl
```
sub_dir/sub_wdl.wdl
```
You zipped
```
zip -r sub_dir.zip sub_dir/
```
I zipped （Files can be decompressed normally）
```
zip sub_dir.zip sub_dir/sub_wdl.wdl
```
 Our project directory has a lot of tasks, and only those used by workflow are zipped. The script is as follows
   ```
   #!/bin/sh
   wdl=$1
   workflow_name=`basename ${wdl} .wdl`
   task_list=`grep "^import" ${wdl} | awk -F '"' '{print $2}'`
   zip ${workflow_name}.zip $task_list
   ```

THX.  FYI.

**Comment by drkennetz** [comment]
@huangzhibo Hi huangzhibo, this makes no difference for me (for cwl). I only contain tools called by the workflow in my zipped directory and it still does not recognize this as a valid workflow.
Example:
```
./echo_cat_wf.cwl
./tools/echo.cwl
./tools/cat.cwl

zip -r tools.zip tools
```
then run:

`java -jar cromwell-44.jar run -i in.yml -p tools.zip --type cwl echo_cat_wf.cwl`
Gives me error.
Thanks,
Dennis

**Comment by Shenglai** [comment]
Hi all,
I've reproduced the problem that @jeremiahsavage shared.
And I've also followed the conversation in #5104, #5183 and https://github.com/EpamLifeSciencesTeam/cromwell/pull/22.

Thank you @myazinn very much for the effort, but I'm wondering if you plan to create a PR here.

**Comment by ZhenyuZ** [comment]
second what @Shenglai just said. It will be great if a PR soon can be created soon

**Comment by myazinn** [comment]
Hi @Shenglai and @ZhenyuZ 
Sorry for the delay.
I made a PR #5259 and will let you know if it is accepted.

**Comment by rhpvorderman** [comment]
I also came across this issue. It should be fixed with #5312 .
