### ISSUE TITLE
concurrent-job-limit not work in local mode

### ISSUE THREAD

**Issue by lozybean** [broadinstitute/cromwell#5359]
the example configure file mentioned in [cromwell document](https://cromwell.readthedocs.io/en/stable/Configuring/) shows 404:  [cromwell.examples.conf](https://github.com/broadinstitute/cromwell/tree/develop/cromwell.examples.conf)

**Comment by lozybean** [comment]
I found the config file in this link [cromwell.examples.conf](https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/cromwell.examples.conf);

**BUT** when I set the `concurrent-job-limit = 2`, and run with `-Dconfig.file=cromwell.conf`，in `local` mode，but cromwell still forks **8** job, it seems the limit not working

**Comment by freeseek** [comment]
I have the exact same issue. First of all, both the [Configuration examples](https://cromwell.readthedocs.io/en/stable/Configuring/#configuration-examples) and [Local](https://cromwell.readthedocs.io/en/stable/backends/Local/) sections of the documentation point to non-existing file https://github.com/broadinstitute/cromwell/tree/develop/cromwell.examples.conf while they should point to https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/cromwell.examples.conf like lozybean pointed out. This is still not fixed in the documentation.

But then I have downloaded the [cromwell.examples.conf](https://raw.githubusercontent.com/broadinstitute/cromwell/develop/cromwell.example.backends/cromwell.examples.conf) file and used it as follows:
```
wget https://raw.githubusercontent.com/broadinstitute/cromwell/develop/cromwell.example.backends/cromwell.examples.conf
sed -i 's/#concurrent-job-limit = 5/concurrent-job-limit = 5/' cromwell.examples.conf
java -Dconfig.file=cromwell.examples.conf -jar cromwell-51.jar run ...
```

And Cromwell on my laptop still spawned 23 job tasks simultaneously. What do I have to do to limit the number of concurrent jobs? This would be very convenient for me to be able to speed up development of my own WDL. Thank you!

**Comment by freeseek** [comment]
Figured out the issue thanks to @cjllanwarne as I actually needed to run the following instead:
```
wget https://raw.githubusercontent.com/broadinstitute/cromwell/develop/cromwell.example.backends/cromwell.examples.conf
sed -i 's/#default = "LocalExample"/default = "LocalExample"/' cromwell.examples.conf
sed -i 's/#concurrent-job-limit = 5/concurrent-job-limit = 5/' cromwell.examples.conf
java -Dconfig.file=cromwell.examples.conf -jar cromwell-51.jar run ...
```

**Comment by zoeward-nz** [comment]
Hi @freeseek , I'm still having the issue?
I have uncommented #default = "LocalExample" to default = "LocalExample"
Changed #concurrent-job-limit = 5 to concurrent-job-limit = 4 (I want 4 jobs to run concurrently)

But it is still running just one job.
Do you have any advice?
